### ISSUE TITLE
CSS Validator

### ISSUE THREAD

**Issue by ryanpurdyca** [ryanpurdyca/dsn1675-saas-website#1] opened 2015-11-19 19:46 UTC
@thomasjbradley

Hi Thomas, I unfortunately didn't get a chance to catch up with you in your office today because there was a line of other in front of me so i'm resorting to github. I'm not entirely sure what these css issues are seen in the link below. I've fixed everything I do understand. Any help would be greatly appreciated :)

https://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fryannicholaspurdy.github.io%2Fdsn1675-saas-website%2F&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en

**Comment by thomasjbradley** [comment] 2015-11-19 21:35
Don't worry about validating the grid, type, or modules CSS they're all good already.

So, the problems are only in your main.css:
- All the viewport and text-size-adjust and stuff should be deleted because it's a duplicate of what's inside modules
- Then there is a single curly brace missing on this line:
  https://github.com/RyanNicholasPurdy/dsn1675-saas-website/blob/gh-pages/css/main.css#L69

**Closed as completed** 2017-01-15 17:23 UTC
